name: "Push to Envoyer"
description: "Triggers a release on Envoyer"
branding:
  icon: "chevrons-up"
  color: "gray-dark"

inputs:
  branch:
    description: "The branch to be deployed"
    required: true
  projectId:
    description: "The Envoyer project id"
    required: true
  token:
    description: "The Envoyer API token"
    required: true
  timeout:
    description: "The timeout in seconds."

runs:
  using: composite
  steps:
    - id: build-action
      name: Build go action
      uses: actions-go/build@v1
      with:
       action_path: ${{ github.action_path }}
       action: ${{ github.action }}
       go-version: "1.21" # defaults to 1.21
    - name: Run my action
      shell: bash
      id: run
      run: ${{ steps.build-action.outputs.install-path }}
      env:
        ACTION_GO_INPUTS: "${{ toJSON(inputs) }}"
