name: "Push to Envoyer"
description: "Triggers a release on Envoyer"
branding:
  icon: "chevrons-up"
  color: "gray-dark"

inputs:
  branch:
    description: "The branch to be deployed"
    required: true
  projectId:
    description: "The Envoyer project id"
    required: true
  token:
    description: "The Envoyer API token"
    required: true

runs:
  using: composite
  steps:
    - name: Deploy project
      uses: fjogeleit/http-request-action@v1.14.0
      with:
        url: "https://envoyer.io/api/projects/${{inputs.projectId}}/deployments"
        bearerToken: ${{ inputs.token}}
        data: '{"from": "branch", "branch": "${{ inputs.branch }}"}'
        customHeaders: '{"Content-Type": "application/json"}'
    - name: List deployments
      uses: fjogeleit/http-request-action@v1.14.0
      id: list-deployments
      with:
        url: "https://envoyer.io/api/projects/${{inputs.projectId}}/deployments"
        bearerToken: ${{ inputs.token}}
        customHeaders: '{"Content-Type": "application/json"}'
        method: 'GET'
    - name: Wait for release
      uses: mydea/action-wait-for-api@v1.0.0
      with:
        url: "https://envoyer.io/api/projects/${{inputs.projectId}}/deployments/${{fromJson(steps.list-deployments.outputs.response).deployments[0].id}}"
        expected-response-field: "deployment.status"
        expected-response-field-value: "finished"
        headers: '{"Authorization":"Bearer ${{ inputs.token}}"}'